### PR TITLE
feat: ✨ Add CLI commands to create registry/world

### LINKED ISSUE #64: Add CLI commands to create registry/world
**Is your feature request related to a problem? Please describe.**

So that the frontend/clients don't need to worry about a world/registry being created, we could have  CLI that allows developer to pre-deploy a registry/world in its cluster of choice

**Describe the solution you'd like**

`bolt world "seed"` command could return an usable world PDA that is initialized on the current cluster

### PR DESCRIPTION
**Pull request by iamnamananand996**
| Status  | Type  | ⚠️ Core Change | Issue |
| :---: | :---: | :---: | :--: |
| Ready| Feature | Yes| [#64](https://github.com/magicblock-labs/bolt/issues/64) |

## Problem

- Frontend/clients don't need to worry about a world/registry being created.
- Need CLI that allows developer to pre-deploy a registry/world in its cluster of choice.

See [#64](https://github.com/magicblock-labs/bolt/issues/64) for a full description

### Examples using the Bolt CLI

Create registry on current cluster 
```
bolt registry
```

Create world on current cluster 
```
bolt world
```

Closes #64

### CODE REVIEW

**Comment by iamnamananand996** [comment]
Hi @crypto-vincent,

for `World PDA`, I have just add the `initialization `from `program template`, do we need expand it more and make it workable or just boilerplate like this is enough.


```rust
fn create_world_template_simple(name: &str, program_path: &Path) -> Files {
    vec![(
        program_path.join("src").join("lib.rs"),
        format!(
            r#"use anchor_lang::prelude::*;

declare_id!("{}");

#[program]
pub mod {} {{
    use super::*;

    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {{
        Ok(())
    }}
}}

#[derive(Accounts)]
pub struct Initialize {{}}
"#,
            get_or_create_program_id(name),
            name.to_snake_case(),
        ),
    )]
}
```

**Comment by iamnamananand996** [comment]
Hi @GabrielePicco, this PR is sitting here from very long time, if you can have look and see what is the actual expectations and add some suggestions.

That will be very helpful for me to proceed further.

**Comment by GabrielePicco** [comment]
Hey @iamnamananand996, the commands to create registry/world don't create a new component/system or template, but rather they should execute transction. Namely it would be the equivalent of running `https://github.com/magicblock-labs/bolt/blob/main/tests/bolt.ts#L111` from Rust

**Comment by iamnamananand996** [comment]
Hi @GabrielePicco, thank you for your valuable suggestion, and guided to correct path, will update the PR with correct changes

**Comment by GabrielePicco** [comment]
Thanks @iamnamananand996 . [authorize](`https://github.com/magicblock-labs/bolt/blob/main/cli/src/lib.rs#L41`) is an example of a command that runs a transaction

**Comment by iamnamananand996** [comment]
> Thanks @iamnamananand996 . authorize is an example of a command that runs a transaction

Hi @GabrielePicco, this comment had really helped.

Now the changes has been updated with the requested solution.
I have done some changes to **world program** also, so I think, It will require re-deploy of world program.

Please have a look, and let me know if you think it will require any further change. Happy to contribute more

**Comment by GabrielePicco** [comment]
Hey @iamnamananand996,
I don’t understand how the `extra_seed` is useful in the context of a registry (there should only be one) or a world instance. What was the rationale behind adding it?

**Comment by iamnamananand996** [comment]
Hi @GabrielePicco, thanks for asking, I had an assumption that, from `CLI app`, user can create `multiple registry` and under those registry they can create `world`.

If I have understood the flow wrong, please help me to understand the correct flow, I will make the changes accordingly.

**Comment by GabrielePicco** [comment]
Thanks for clarifying, @iamnamananand996. The idea is that there is currently a single registry (and I would keep it that way) so that everyone can discover all the existing world instances. Infinite world instances can already be created, so I don't think we need an extra registry in either of the two cases.

**Comment by iamnamananand996** [comment]
Hi @iamnamananand996, thanks for answering and make me understand the flow, I will make the changes accordingly.

**Comment by iamnamananand996** [comment]
Hi @GabrielePicco, I have update the PR with the flow required. This is ready for review now.

**Review by GabrielePicco — APPROVED** [review]
Thanks @iamnamananand996, LGTM!

**Pull request merged**
