### PR TITLE
feat: add missing apply function in sdk

### PR DESCRIPTION
**Pull request by obstoody**
## Problem

I noticed that the `apply` function used in world programs was missing from the SDK, so I added it.

## Solution

Added `Apply` function in `sdk/world/transactions.ts` file.

## Before & After Screenshots

**BEFORE**:
None

**AFTER**:
image

### CODE REVIEW

**Review by GabrielePicco — APPROVED** [review]

**Comment by notdanilo** [comment]
I will add tests for this before we can merge

**Comment by obstoody** [comment]
Thanks team!

**Comment by obstoody** [comment]
Anything I can support adding test codes?

**Comment by notdanilo** [comment]
@obstoody the test is ready in #103. I am waiting for @GabrielePicco to review it. I am fixing other small issues and I am planning to make a new release asap. Thanks a lot for your contribution!

**Comment by notdanilo** [comment]
Your contribution was just merged in #103. Thanks @obstoody!

**Pull request closed without merging**
